### ISSUE TITLE
`cancelOrder()` always results in "Not logged in" error [ 401 ]  +fix

### ISSUE THREAD

**Issue by azidyn** [tiagosiebler/ftx-api#10]
`cancelOrder()` and I'd guess any call to a non-GET http method when interal `params` object is undefined/null results in a quoted empty string being used to form a (bad) `signature_payload`. These two lines are the culprit:

https://github.com/tiagosiebler/ftx-api/blob/master/src/util/requestWrapper.ts#L191-L192

e.g. should be something like 

```js
    const paramsPayload = method == 'GET' ? params : ( params ? JSON.stringify(params) : '' );
```

cheers!

**Comment by tiagosiebler** [comment]
Good catch, that's a sneaky one! Pushed a beta release, can you confirm if it's working now?
```
npm install ftx-api@1.0.7-beta.1
```

Thanks!

**Comment by azidyn** [comment]
Yep that works, confirmed 

sent a USDT tip to your erc20 wallet btw

**Comment by tiagosiebler** [comment]
> Yep that works, confirmed
> 
> sent a USDT tip to your erc20 wallet btw

Thank you! Just to confirm that the latest version (v1.0.7) now contains this fix.
