### ISSUE TITLE
unable to add externalReferralProgram

### ISSUE THREAD

**Issue by Merrick17** [tiagosiebler/ftx-api#12]
I am not  able to externalReferralProgram as an option

**Comment by tiagosiebler** [comment]
I've pushed a fix - try the latest version & let me know: `npm install ftx-api@latest`

**Comment by Merrick17** [comment]
@tiagosiebler  please update the example for using it it doesn't display in autocorrect it needs to be submitted as an optional params

**Comment by Merrick17** [comment]
@tiagosiebler shows can not login

**Comment by tiagosiebler** [comment]
Seems to be fixed in #14. If not, let me know.
