### ISSUE TITLE
Bug in `getPositions()` (401 Unauthorized)

### ISSUE THREAD

**Issue by azidyn** [tiagosiebler/ftx-api#4]
Not sure if this is a bug or I'm doing something wrong but getPositions() fails with a 401.

If I bypass and call directly via `client.requestWrapper.get('positions');` it works correctly.

**Comment by tiagosiebler** [comment]
This sounds like an unusual bug actually. If you don't provide any parameters in your `getPositions()` call, it actually triggers the equivalent of `requestWrapper.get('positions?');`:
https://github.com/tiagosiebler/ftx-api/blob/master/src/rest-client.ts#L171-L172

Could you try if the issue happens via this too? `client.requestWrapper.get('positions?');`

**Comment by azidyn** [comment]
Can confirm that `client.requestWrapper.get('positions?')` (with question mark) produces the 401 error. Removing the `?` fixes the problem, how strange!

**Comment by tiagosiebler** [comment]
Thanks for confirming! It was silly of me to suffix endpoints with `?` even when an optional parameter isn't included, although I wasn't expecting that to cause any issues with signed requests... I've pushed a fix that seems to be working on my end.

Can you try the latest version (v1.0.3) and confirm?
```
npm install ftx-api@latest
```

**Comment by azidyn** [comment]
Yes, can confirm the fix is working correctly. (Sorry for delay!)
