### ISSUE TITLE
websocket-client didn't pass subaccount name to authenticate

### ISSUE THREAD

**Issue by kangchihlun** [tiagosiebler/ftx-api#6]
https://github.com/tiagosiebler/ftx-api/blob/6d57ba596d6b11c15e53e206b2b48a1977422886/src/websocket-client.ts#L173

message for private channel of sub account didn't work.

**Comment by tiagosiebler** [comment]
@kangchihlun good catch - I've pushed a fix for this. Can you try the latest version (v1.0.4) and confirm?
```
npm install ftx-api@latest
```

Thanks for reporting this!

**Comment by kangchihlun** [comment]
It works ! much appreciated!
