### ISSUE TITLE
Test net for ftx US?

### ISSUE THREAD

**Issue by kenchambers** [tiagosiebler/ftx-api#62]
I'm having a lot of trouble finding a testnet for FTX US, do you guys know if it exists?

I see `livenet: true` option fot the WS client, so It seems like there might be one.

**Comment by kenchambers** [comment]
sorry I know this is not an actual issue with your API, it's great btw.

**Comment by tiagosiebler** [comment]
The ws parameter is a bit misleading - I must've forgotten to remove it when building this flavour of my connectors. 

As far as I know, FTX does not have a testnet (not on .com nor .us). If you'd like an official confirmation, you could try asking in their official API telegram group: https://t.me/ftx_api_support
