### ISSUE TITLE
[ReferenceError: RestClient is not defined] Using webpacked ftxapi 

### ISSUE THREAD

**Issue by 0x520x650x78** [tiagosiebler/ftx-api#64]
I encountered this error while trying to integrate this package in browser. After running webpack and put it in browser script, I got ReferenceError: RestClient is not defined error.

Below is a snippet of code that I run: 

<p>
      <script type="module" src="./src/ftxapi.js"></script>
      <script src="https://cdn.jsdelivr.net/npm/web3@latest/dist/web3.min.js"></script>
      <link rel="stylesheet" href="style.css"/>
</p>

const test_client = new RestClient(credential.test[0], credential.test[1], {subAccountName: 'test'});

The webpacked .js file is as following: 
https://gist.githubusercontent.com/0x520x650x78/cc6538ac9c6b913ac4ebba72a876c0df/raw/cd0f4f2afaf8b129341e2f7855ccb18615f7c9b8/ftxapi

Thanks!

**Comment by tiagosiebler** [comment]
In the webpack config, the library is packaged as a global under the name `ftxapi` when loaded in the browser:
https://github.com/tiagosiebler/ftx-api/blob/master/webpack/webpack.config.js#L12

You should be able to do something like
```javascript
<script type="module" src="./src/ftxapi.js"></script>
<script src="https://cdn.jsdelivr.net/npm/web3@latest/dist/web3.min.js"></script>

const { RestClient } = ftxapi;// or window.ftxapi

const test_client = new RestClient(credential.test[0], credential.test[1], {subAccountName: 'test'});
```

**Comment by tiagosiebler** [comment]
Could it be CORS? You could try to catch the exception and logging it for more detail, and/or check the network tab in your browser's dev tools to see what request happened and if it failed.

**Comment by 0x520x650x78** [comment]
> 

OK I will take a look and update the progress I make here. (Maybe a pull request if I spot where the issue is)

Thanks for the reference and the great package.

**Comment by 0x520x650x78** [comment]
OK I found the issue. It is the CORs problem and since I'm using the browser for the dashboard, I just need to allow all CORs and then the issue will be resolved.
