### ISSUE TITLE
Unsubscribing WS channel not removing from the collection

### ISSUE THREAD

**Issue by slpn1** [tiagosiebler/ftx-api#8]
Hi,

This is awesome thanks. I was coding something similar myself not long ago, but no need now. How do I donate?

I am having one issue with ws. When I subscribe to a ticker, then unsubscribe then subscribe to another ticker, it doesn't seem to forget the one I unsubscribed from and resubscribes it again with the second one.

Screenshot attached. Where it says SUBBING pair I am only sending one subscribe command, but the old unsubscribed one is still in the collection. Any ideas? Thanks.

<img width="662" alt="Screenshot 2021-04-30 at 14 30 42" src="https://user-images.githubusercontent.com/24227821/116702627-3c46fe80-a9c1-11eb-84b6-f9f6a328d806.png">

**Comment by tiagosiebler** [comment]
Interesting find! Thanks for reporting this, caught two bugs while investigating - can you try the beta release with a fix?
```
npm install ftx-api@1.0.5-beta.2
```

Details here if you're curious: https://github.com/tiagosiebler/ftx-api/pull/9

Regarding donations - always appreciated on my ETH (ERC20) address, unless you have a preferred alternative: `0xd773d8e6a50758e1ada699bb6c4f98bb4abf82da`

Let me know once you've given the beta some testing. If all is well I'll publish it to release properly. Thanks!

**Comment by slpn1** [comment]
Great, thanks! A real quick look shows things to be working as expected. I’ll carry on developing around this version for a little bit and let you know if I spot anything.

Dropped a small donation to your address.

Cheers,
Simon

From: Tiago ***@***.***>
Reply to: tiagosiebler/ftx-api ***@***.***>
Date: Friday, 30 April 2021 at 23:10
To: tiagosiebler/ftx-api ***@***.***>
Cc: slpn1 ***@***.***>, Author ***@***.***>
Subject: Re: [tiagosiebler/ftx-api] Unsubscribing WS channel not removing from the collection (#8)


Interesting find! Thanks for reporting this, caught two bugs while investigating - can you try the beta release with a fix?

npm install ***@***.***

Details here if you're curious: #9<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Ftiagosiebler%2Fftx-api%2Fpull%2F9&data=04%7C01%7C%7Cb11fa03f24624d98a88108d90c24b8c4%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637554174128052290%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=KpOOQ25fnNjdSX48gTHu9dsk184fKUSHJqkmuvt2JVY%3D&reserved=0>

Regarding donations - always appreciated on my ETH (ERC20) address, unless you have a preferred alternative: 0xd773d8e6a50758e1ada699bb6c4f98bb4abf82da

Let me know once you've given the beta some testing. If all is well I'll publish it to release properly. Thanks!

**Comment by tiagosiebler** [comment]
Moved from beta to the latest release. Thanks!
