### ISSUE TITLE
Possible to getUsdValueSnapshots history for subaccounts?

### ISSUE THREAD

**Issue by dsldsl** [tiagosiebler/ftx-api#95]
Thank you so much for this!  Do you know if it's possible to getUsdValueSnapshots for subaccounts?  it's undocumented so I am trying to play with the url or the params.  thank you!

<img width="816" alt="image" src="https://user-images.githubusercontent.com/50015/201001990-31aaabb8-d0c2-4675-9a43-a4c09e271a34.png">

**Comment by tiagosiebler** [comment]
For these undocumented endpoints, try it in the browser. Navigate on the website to the functionality you're looking for (select your subaccount and look for the same data in the browser) and check for network requests in developer tools. This is how the other undocumented endpoints were found so far. 

Hopefully this works the same as any other endpoint for subaccounts (using the `FTX-SUBACCOUNT` header). If so, you can just pass the subaccount name in the rest options (3rd parameter of the rest client):
https://github.com/tiagosiebler/ftx-api/blob/5bcec08156ab6ba5510e5947549594b9f264ef8e/src/util/requestUtils.ts#L26
